# -*- coding: utf-8 -*-
"""Assignment_1_2671510_jyotiran_mondal_joy_AI_security_for_healthcare

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cvv1sDGnXUJdyRnqnU0u0DwcmPod1K_e
"""

# Import required libraries

import pandas as pd
import numpy as np

from sklearn.datasets import load_breast_cancer

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC

from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    confusion_matrix,
    roc_auc_score
)

import matplotlib.pyplot as plt
import seaborn as sns

"""## Phase A: Data Preprocessing

Convert the raw Bunch object into a Pandas DataFrame with correct feature names.
"""

# Load dataset

data = load_breast_cancer()

# Convert to dataframe

df = pd.DataFrame(data.data, columns=data.feature_names)

# Add target column

df['target'] = data.target


# Display first rows

df.head()

"""Preprocessing: Check for missing values (though this dataset is clean, the code must show the check).

"""

# Check missing values

df.isnull().sum()

"""Train test split"""

# Create DataFrame
X = pd.DataFrame(data.data, columns=data.feature_names)
y = pd.Series(data.target, name="target")


X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

"""Feature Scaling: Apply StandardScaler.

"""

scaler = StandardScaler()

# Fit on training data and transform it
X_train_scaled = scaler.fit_transform(X_train)

# Transform testing data
X_test_scaled = scaler.transform(X_test)


print("Feature Scaling Completed!")

"""## Phase B: Model Implementation: LR, RF, SVM

**Logistic Regression**
"""

from sklearn.linear_model import LogisticRegression

# Create model
lr_model = LogisticRegression(max_iter=5000, random_state=42)

# Train model
lr_model.fit(X_train_scaled, y_train)

# Make predictions
lr_predictions = lr_model.predict(X_test_scaled)

print("Logistic Regression model trained successfully!")

"""**Random Forest**"""

from sklearn.ensemble import RandomForestClassifier

# Create model
rf_model = RandomForestClassifier(
    n_estimators=100,
    random_state=42
)

# Train model
rf_model.fit(X_train, y_train)

# Make predictions
rf_predictions = rf_model.predict(X_test)

print("Random Forest model trained successfully!")

"""**Support Vector Machine (SVM)**"""

from sklearn.svm import SVC

# Create model
svm_model = SVC(
    kernel="rbf",
    random_state=42
)

# Train model
svm_model.fit(X_train_scaled, y_train)

# Make predictions
svm_predictions = svm_model.predict(X_test_scaled)

print("SVM model trained successfully!")

"""## Phase C: Evaluation: Collect metrics: Accuracy, Precision, Recall, F1-score

**Compare All Models**
"""

results = pd.DataFrame({
    "Model": [
        "Logistic Regression",
        "Random Forest",
        "SVM"
    ],

    "Accuracy": [
        accuracy_score(y_test, lr_predictions),
        accuracy_score(y_test, rf_predictions),
        accuracy_score(y_test, svm_predictions)
    ],

    "Precision": [
        precision_score(y_test, lr_predictions),
        precision_score(y_test, rf_predictions),
        precision_score(y_test, svm_predictions)
    ],

    "Recall": [
        recall_score(y_test, lr_predictions),
        recall_score(y_test, rf_predictions),
        recall_score(y_test, svm_predictions)
    ],

    "F1-Score": [
        f1_score(y_test, lr_predictions),
        f1_score(y_test, rf_predictions),
        f1_score(y_test, svm_predictions)
    ]
})

print(results)

"""## Phase D: Plots and figure"""

import matplotlib.pyplot as plt
from sklearn.metrics import ConfusionMatrixDisplay

models = {
    "Logistic_Regression": (lr_model, X_test_scaled),
    "Random_Forest": (rf_model, X_test),
    "SVM": (svm_model, X_test_scaled)
}

for name, (model, X_data) in models.items():

    predictions = model.predict(X_data)

    cm = confusion_matrix(y_test, predictions)

    display = ConfusionMatrixDisplay(
        confusion_matrix=cm,
        display_labels=data.target_names
    )

    display.plot()
    plt.title(f"{name} Confusion Matrix")

    plt.savefig(f"{name}_confusion_matrix.png")

    plt.show()
    plt.close()

import matplotlib.pyplot as plt

results.plot(
    x="Model",
    y=["Accuracy", "Precision", "Recall", "F1-Score"],
    kind="bar",
    figsize=(10, 6)
)

plt.title("Model Performance Comparison")
plt.ylabel("Score")
plt.ylim(0, 1)
plt.xticks(rotation=0)

plt.tight_layout()

plt.savefig("model_comparison.png")

plt.show()
plt.close()

"""Save model"""

import joblib

# Save your best model
joblib.dump(lr_model, "model.pkl")

# Save scaler
joblib.dump(scaler, "scaler.pkl")

"""Host into gradio"""

import gradio as gr
import pandas as pd

# Load feature names
data = load_breast_cancer()
feature_names = data.feature_names.tolist()

def predict(*inputs):

    # Create DataFrame
    input_data = pd.DataFrame(
        [inputs],
        columns=feature_names
    )

    # Scale the input
    input_scaled = scaler.transform(input_data)

    # Prediction
    prediction = lr_model.predict(input_scaled)[0]

    # Probability
    probability = lr_model.predict_proba(input_scaled)[0]

    # Result
    result = "Benign" if prediction == 1 else "Malignant"

    return {
        "Malignant": float(probability[0]),
        "Benign": float(probability[1])
    }


# Create input fields automatically
inputs = [
    gr.Number(label=feature)
    for feature in feature_names
]


# Create Gradio interface
app = gr.Interface(
    fn=predict,
    inputs=inputs,
    outputs=gr.Label(num_top_classes=2),
    title="Breast Cancer Disease Prediction",
    description="Enter patient medical measurements to predict whether the tumor is Malignant or Benign."
)

app.launch(share=True)